<a href="https://colab.research.google.com/github/manojmulammagari/Q-Skill-Internship-Projects/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Operations Tool
This tool demonstrates basic and advanced matrix operations using NumPy.

In [1]:
import numpy as np

# Define sample matrices for the operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]


In [2]:
# Basic Arithmetic: Addition and Subtraction
sum_result = np.add(A, B)
diff_result = np.subtract(A, B)

print("Addition (A + B):")
print(sum_result)
print("\nSubtraction (A - B):")
print(diff_result)

Addition (A + B):
[[ 6  8]
 [10 12]]

Subtraction (A - B):
[[-4 -4]
 [-4 -4]]


In [3]:
# Matrix Multiplication (Dot Product)
prod_result = np.dot(A, B)

print("Matrix Multiplication (A * B):")
print(prod_result)

Matrix Multiplication (A * B):
[[19 22]
 [43 50]]


In [4]:
# Transpose and Determinant
transpose_A = np.transpose(A)
det_A = np.linalg.det(A)

print("Transpose of A:")
print(transpose_A)
print(f"\nDeterminant of A: {det_A}")

Transpose of A:
[[1 3]
 [2 4]]

Determinant of A: -2.0000000000000004


In [5]:
# Matrix Inverse
try:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:")
    print(inv_A)
except np.linalg.LinAlgError:
    print("Matrix A is not invertible.")

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [11]:
def get_matrix(name):
    print(f"Enter 4 numbers for 2x2 Matrix {name} (space-separated):")
    data = input().split()
    return np.array(data, dtype=float).reshape(2, 2)

print("--- Matrix Tool Menu ---")
print("1. Addition")
print("2. Subtraction")
print("3. Multiplication")
print("4. Transpose")
print("5. Determinant")

choice = input("Select an operation (1-5): ")

if choice in ['1', '2', '3']:
    m1 = get_matrix("A")
    m2 = get_matrix("B")
    if choice == '1':
        print("\nResult (Addition):\n", m1 + m2)
    elif choice == '2':
        print("\nResult (Subtraction):\n", m1 - m2)
    elif choice == '3':
        print("\nResult (Multiplication):\n", np.dot(m1, m2))

elif choice in ['4', '5']:
    m = get_matrix("A")
    if choice == '4':
        print("\nResult (Transpose):\n", m.T)
    elif choice == '5':
        print("\nResult (Determinant):", np.linalg.det(m))
else:
    print("Invalid choice selected.")

--- Matrix Tool Menu ---
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
Select an operation (1-5): 1
Enter 4 numbers for 2x2 Matrix A (space-separated):
3 4 6 8
Enter 4 numbers for 2x2 Matrix B (space-separated):
5 8 3 6

Result (Addition):
 [[ 8. 12.]
 [ 9. 14.]]
